# Generated by Django 5.1 on 2024-08-29 10:34

import pathlib

import django.core.files.storage
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import utils.files


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "rosters",
            "0002_remove_rosteruserschedule_roster_user_schedule_date_unique_constraint_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("date_deleted", models.DateTimeField(blank=True, null=True)),
                (
                    "capture_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            location=pathlib.PureWindowsPath("D:/rollcall/src")
                        ),
                        upload_to=utils.files.RenameFile(
                            "files/attendance/{instance.roster_user_schedule.user_id}/{instance.date_created}.{extension}"
                        ),
                        validators=[
                            utils.files.ValidateFileSize(max_file_size=10),
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=("jpeg", "jpg", "png")
                            ),
                        ],
                    ),
                ),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "roster_user_schedule",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rosters.rosteruserschedule",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendances",
            },
        ),
    ]
